default:
#	pdflatex lec1
#	pdflatex lec1
#	pdflatex lec2
#	pdflatex lec2
#	pdflatex lec3
#	pdflatex lec3
	pdflatex --synctex=1 lec4
	pdflatex --synctex=1 lec4
#	pdflatex lec5
#	pdflatex lec5
#	pdflatex lec6
#	pdflatex lec6
#	pdflatex lec7
#	pdflatex lec7
#	pdflatex lec8
#	pdflatex lec8
#	pdflatex lec11
#	pdflatex lec11
#	pdflatex lec13
#	pdflatex lec13

5:
	pdflatex lec5
	pdflatex lec5
