default:
#	pdflatex handson1
#	pdflatex handson2
#	pdflatex handson3
#	pdflatex handson4
#	pdflatex handson5
#	pdflatex handson6
	pdflatex handson7
	pdflatex handson7_solutions
	pdflatex handson10
	pdflatex handson10_solutions
